### PR TITLE
Fix missing logs for appserver

### PR DESCRIPTION
**Pull request by RKushnir**
See https://github.com/puma/puma/commit/03ed48ca903879f3b9a649f5df1cf9d6577ef3d2

### CODE REVIEW

**Comment by dziemba** [comment]
Isn't that something the app should do itself when needed? Otherwise this produces a lot of noise, when not needed. Especially if you have a lot of status check requests.

**Comment by RKushnir** [comment]
I don't see a point in feeding the output to `logger` if there's never any output. You can filter the app logs out by tag if necessary.

**Comment by RKushnir** [comment]
Also, that behavior has changed because of the puma update, not because we explicitly decided it.

**Comment by dziemba** [comment]
Ah okay, so this suppresses _all_ app log output? That's not what we want, of course.

**Comment by RKushnir** [comment]
Exactly.

**Comment by dziemba** [comment]
🍄 

(please add the change to `CHANGELOG` and squash-merge when tests are green)

**Pull request merged**
