### PR TITLE
Update Circleci config

### PR DESCRIPTION
**Pull request by tsujigiri**

### CODE REVIEW

**Review by itsDustin — APPROVED** [review]
🐔

**Comment by hwartig** [comment]
@tsujigiri Regarding the circle-ci build error we had a similar issue with the other repos as the v2 uses a more recent docker version which has different parameters

**Comment by tsujigiri** [comment]
@hwartig There was a permission issue with the `.bundle` directory. I changed it so it copies the whole app, and then sets the owner for the whole directory. I'm not sure it had anything to do with docker. Maybe bundler?

**EDIT**: There **was** another issue with the `wget` requests, which I had to change.

**Comment by hwartig** [comment]
@tsujigiri Sorry for not being clear. I'm referring to [master build being broken](https://circleci.com/gh/ad2games/docker-rails/389). 
Screenshot 2019-05-24 at 20 25 27

See https://github.com/ad2games/docker-rails/pull/29 for how I think it could be fixed.

**Comment by tsujigiri** [comment]
@hwartig Ah! Got it! :+1:

**Pull request merged**
